-- ============================================================================
-- ACT Data Platform - Consolidated RAW Layer Validation
-- File: snowflake/sql/027_validate_raw_layer.sql
--
-- Purpose:
--   Validate the complete RAW ingestion framework after implementing all
--   eight ACT source entities.
--
-- Checks:
--   1. Landing / History / Current row counts
--   2. Unprocessed landing rows
--   3. Duplicate business keys in CURRENT
--   4. Null business keys in CURRENT
--   5. Basic per-study distribution
--
-- This script does NOT modify data.
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE ACT_DB;
USE SCHEMA RAW;


-- ============================================================================
-- 1. ROW COUNT SUMMARY
-- ============================================================================

SELECT 'STUDY' AS ENTITY, 'LANDING' AS LAYER, COUNT(*) AS ROW_COUNT
FROM ACT_DB.RAW.LND_STUDY
UNION ALL
SELECT 'STUDY', 'HISTORY', COUNT(*)
FROM ACT_DB.RAW.RAW_STUDY_HISTORY
UNION ALL
SELECT 'STUDY', 'CURRENT', COUNT(*)
FROM ACT_DB.RAW.RAW_STUDY_CURRENT

UNION ALL
SELECT 'SITE', 'LANDING', COUNT(*)
FROM ACT_DB.RAW.LND_SITE
UNION ALL
SELECT 'SITE', 'HISTORY', COUNT(*)
FROM ACT_DB.RAW.RAW_SITE_HISTORY
UNION ALL
SELECT 'SITE', 'CURRENT', COUNT(*)
FROM ACT_DB.RAW.RAW_SITE_CURRENT

UNION ALL
SELECT 'SUBJECT', 'LANDING', COUNT(*)
FROM ACT_DB.RAW.LND_SUBJECT
UNION ALL
SELECT 'SUBJECT', 'HISTORY', COUNT(*)
FROM ACT_DB.RAW.RAW_SUBJECT_HISTORY
UNION ALL
SELECT 'SUBJECT', 'CURRENT', COUNT(*)
FROM ACT_DB.RAW.RAW_SUBJECT_CURRENT

UNION ALL
SELECT 'VISIT', 'LANDING', COUNT(*)
FROM ACT_DB.RAW.LND_VISIT
UNION ALL
SELECT 'VISIT', 'HISTORY', COUNT(*)
FROM ACT_DB.RAW.RAW_VISIT_HISTORY
UNION ALL
SELECT 'VISIT', 'CURRENT', COUNT(*)
FROM ACT_DB.RAW.RAW_VISIT_CURRENT

UNION ALL
SELECT 'ADVERSE_EVENT', 'LANDING', COUNT(*)
FROM ACT_DB.RAW.LND_ADVERSE_EVENT
UNION ALL
SELECT 'ADVERSE_EVENT', 'HISTORY', COUNT(*)
FROM ACT_DB.RAW.RAW_ADVERSE_EVENT_HISTORY
UNION ALL
SELECT 'ADVERSE_EVENT', 'CURRENT', COUNT(*)
FROM ACT_DB.RAW.RAW_ADVERSE_EVENT_CURRENT

UNION ALL
SELECT 'LAB_RESULT', 'LANDING', COUNT(*)
FROM ACT_DB.RAW.LND_LAB_RESULT
UNION ALL
SELECT 'LAB_RESULT', 'HISTORY', COUNT(*)
FROM ACT_DB.RAW.RAW_LAB_RESULT_HISTORY
UNION ALL
SELECT 'LAB_RESULT', 'CURRENT', COUNT(*)
FROM ACT_DB.RAW.RAW_LAB_RESULT_CURRENT

UNION ALL
SELECT 'PROTOCOL_DEVIATION', 'LANDING', COUNT(*)
FROM ACT_DB.RAW.LND_PROTOCOL_DEVIATION
UNION ALL
SELECT 'PROTOCOL_DEVIATION', 'HISTORY', COUNT(*)
FROM ACT_DB.RAW.RAW_PROTOCOL_DEVIATION_HISTORY
UNION ALL
SELECT 'PROTOCOL_DEVIATION', 'CURRENT', COUNT(*)
FROM ACT_DB.RAW.RAW_PROTOCOL_DEVIATION_CURRENT

UNION ALL
SELECT 'DATA_QUERY', 'LANDING', COUNT(*)
FROM ACT_DB.RAW.LND_DATA_QUERY
UNION ALL
SELECT 'DATA_QUERY', 'HISTORY', COUNT(*)
FROM ACT_DB.RAW.RAW_DATA_QUERY_HISTORY
UNION ALL
SELECT 'DATA_QUERY', 'CURRENT', COUNT(*)
FROM ACT_DB.RAW.RAW_DATA_QUERY_CURRENT

ORDER BY ENTITY, LAYER;


-- ============================================================================
-- 2. UNPROCESSED LANDING ROWS
--
-- Expected after successful processing:
--   UNPROCESSED_ROWS = 0 for every entity.
-- ============================================================================

SELECT 'STUDY' AS ENTITY, COUNT(*) AS UNPROCESSED_ROWS
FROM ACT_DB.RAW.LND_STUDY
WHERE PROCESSED_FLAG = FALSE

UNION ALL
SELECT 'SITE', COUNT(*)
FROM ACT_DB.RAW.LND_SITE
WHERE PROCESSED_FLAG = FALSE

UNION ALL
SELECT 'SUBJECT', COUNT(*)
FROM ACT_DB.RAW.LND_SUBJECT
WHERE PROCESSED_FLAG = FALSE

UNION ALL
SELECT 'VISIT', COUNT(*)
FROM ACT_DB.RAW.LND_VISIT
WHERE PROCESSED_FLAG = FALSE

UNION ALL
SELECT 'ADVERSE_EVENT', COUNT(*)
FROM ACT_DB.RAW.LND_ADVERSE_EVENT
WHERE PROCESSED_FLAG = FALSE

UNION ALL
SELECT 'LAB_RESULT', COUNT(*)
FROM ACT_DB.RAW.LND_LAB_RESULT
WHERE PROCESSED_FLAG = FALSE

UNION ALL
SELECT 'PROTOCOL_DEVIATION', COUNT(*)
FROM ACT_DB.RAW.LND_PROTOCOL_DEVIATION
WHERE PROCESSED_FLAG = FALSE

UNION ALL
SELECT 'DATA_QUERY', COUNT(*)
FROM ACT_DB.RAW.LND_DATA_QUERY
WHERE PROCESSED_FLAG = FALSE

ORDER BY ENTITY;


-- ============================================================================
-- 3. DUPLICATE BUSINESS KEYS IN CURRENT
--
-- Every query below should return ZERO rows.
-- ============================================================================

-- STUDY key: STUDY_ID
SELECT
    'STUDY' AS ENTITY,
    STUDY_ID AS KEY_1,
    NULL AS KEY_2,
    COUNT(*) AS ROW_COUNT
FROM ACT_DB.RAW.RAW_STUDY_CURRENT
GROUP BY STUDY_ID
HAVING COUNT(*) > 1;


-- SITE key: STUDY_ID + SITE_ID
SELECT
    'SITE' AS ENTITY,
    STUDY_ID AS KEY_1,
    SITE_ID AS KEY_2,
    COUNT(*) AS ROW_COUNT
FROM ACT_DB.RAW.RAW_SITE_CURRENT
GROUP BY STUDY_ID, SITE_ID
HAVING COUNT(*) > 1;


-- SUBJECT key: STUDY_ID + SUBJECT_ID
SELECT
    'SUBJECT' AS ENTITY,
    STUDY_ID AS KEY_1,
    SUBJECT_ID AS KEY_2,
    COUNT(*) AS ROW_COUNT
FROM ACT_DB.RAW.RAW_SUBJECT_CURRENT
GROUP BY STUDY_ID, SUBJECT_ID
HAVING COUNT(*) > 1;


-- VISIT key: STUDY_ID + VISIT_ID
SELECT
    'VISIT' AS ENTITY,
    STUDY_ID AS KEY_1,
    VISIT_ID AS KEY_2,
    COUNT(*) AS ROW_COUNT
FROM ACT_DB.RAW.RAW_VISIT_CURRENT
GROUP BY STUDY_ID, VISIT_ID
HAVING COUNT(*) > 1;


-- ADVERSE_EVENT key: STUDY_ID + AE_ID
SELECT
    'ADVERSE_EVENT' AS ENTITY,
    STUDY_ID AS KEY_1,
    AE_ID AS KEY_2,
    COUNT(*) AS ROW_COUNT
FROM ACT_DB.RAW.RAW_ADVERSE_EVENT_CURRENT
GROUP BY STUDY_ID, AE_ID
HAVING COUNT(*) > 1;


-- LAB_RESULT key: STUDY_ID + LAB_ID
SELECT
    'LAB_RESULT' AS ENTITY,
    STUDY_ID AS KEY_1,
    LAB_ID AS KEY_2,
    COUNT(*) AS ROW_COUNT
FROM ACT_DB.RAW.RAW_LAB_RESULT_CURRENT
GROUP BY STUDY_ID, LAB_ID
HAVING COUNT(*) > 1;


-- PROTOCOL_DEVIATION key: STUDY_ID + DEVIATION_ID
SELECT
    'PROTOCOL_DEVIATION' AS ENTITY,
    STUDY_ID AS KEY_1,
    DEVIATION_ID AS KEY_2,
    COUNT(*) AS ROW_COUNT
FROM ACT_DB.RAW.RAW_PROTOCOL_DEVIATION_CURRENT
GROUP BY STUDY_ID, DEVIATION_ID
HAVING COUNT(*) > 1;


-- DATA_QUERY key: STUDY_ID + QUERY_ID
SELECT
    'DATA_QUERY' AS ENTITY,
    STUDY_ID AS KEY_1,
    QUERY_ID AS KEY_2,
    COUNT(*) AS ROW_COUNT
FROM ACT_DB.RAW.RAW_DATA_QUERY_CURRENT
GROUP BY STUDY_ID, QUERY_ID
HAVING COUNT(*) > 1;


-- ============================================================================
-- 4. NULL BUSINESS-KEY CHECKS IN CURRENT
--
-- Expected:
--   NULL_KEY_ROWS = 0 for every entity.
-- ============================================================================

SELECT 'STUDY' AS ENTITY, COUNT(*) AS NULL_KEY_ROWS
FROM ACT_DB.RAW.RAW_STUDY_CURRENT
WHERE STUDY_ID IS NULL

UNION ALL
SELECT 'SITE', COUNT(*)
FROM ACT_DB.RAW.RAW_SITE_CURRENT
WHERE STUDY_ID IS NULL OR SITE_ID IS NULL

UNION ALL
SELECT 'SUBJECT', COUNT(*)
FROM ACT_DB.RAW.RAW_SUBJECT_CURRENT
WHERE STUDY_ID IS NULL OR SUBJECT_ID IS NULL

UNION ALL
SELECT 'VISIT', COUNT(*)
FROM ACT_DB.RAW.RAW_VISIT_CURRENT
WHERE STUDY_ID IS NULL OR VISIT_ID IS NULL

UNION ALL
SELECT 'ADVERSE_EVENT', COUNT(*)
FROM ACT_DB.RAW.RAW_ADVERSE_EVENT_CURRENT
WHERE STUDY_ID IS NULL OR AE_ID IS NULL

UNION ALL
SELECT 'LAB_RESULT', COUNT(*)
FROM ACT_DB.RAW.RAW_LAB_RESULT_CURRENT
WHERE STUDY_ID IS NULL OR LAB_ID IS NULL

UNION ALL
SELECT 'PROTOCOL_DEVIATION', COUNT(*)
FROM ACT_DB.RAW.RAW_PROTOCOL_DEVIATION_CURRENT
WHERE STUDY_ID IS NULL OR DEVIATION_ID IS NULL

UNION ALL
SELECT 'DATA_QUERY', COUNT(*)
FROM ACT_DB.RAW.RAW_DATA_QUERY_CURRENT
WHERE STUDY_ID IS NULL OR QUERY_ID IS NULL

ORDER BY ENTITY;


-- ============================================================================
-- 5. CURRENT ROWS BY STUDY
-- ============================================================================

SELECT 'SITE' AS ENTITY, STUDY_ID, COUNT(*) AS CURRENT_ROWS
FROM ACT_DB.RAW.RAW_SITE_CURRENT
GROUP BY STUDY_ID

UNION ALL
SELECT 'SUBJECT', STUDY_ID, COUNT(*)
FROM ACT_DB.RAW.RAW_SUBJECT_CURRENT
GROUP BY STUDY_ID

UNION ALL
SELECT 'VISIT', STUDY_ID, COUNT(*)
FROM ACT_DB.RAW.RAW_VISIT_CURRENT
GROUP BY STUDY_ID

UNION ALL
SELECT 'ADVERSE_EVENT', STUDY_ID, COUNT(*)
FROM ACT_DB.RAW.RAW_ADVERSE_EVENT_CURRENT
GROUP BY STUDY_ID

UNION ALL
SELECT 'LAB_RESULT', STUDY_ID, COUNT(*)
FROM ACT_DB.RAW.RAW_LAB_RESULT_CURRENT
GROUP BY STUDY_ID

UNION ALL
SELECT 'PROTOCOL_DEVIATION', STUDY_ID, COUNT(*)
FROM ACT_DB.RAW.RAW_PROTOCOL_DEVIATION_CURRENT
GROUP BY STUDY_ID

UNION ALL
SELECT 'DATA_QUERY', STUDY_ID, COUNT(*)
FROM ACT_DB.RAW.RAW_DATA_QUERY_CURRENT
GROUP BY STUDY_ID

ORDER BY ENTITY, STUDY_ID;


-- ============================================================================
-- 6. FINAL STUDY CURRENT VIEW
-- ============================================================================

SELECT
    STUDY_ID,
    STUDY_NAME,
    PHASE,
    TARGET_SUBJECTS,
    UPDATED_AT,
    INGESTED_AT
FROM ACT_DB.RAW.RAW_STUDY_CURRENT
ORDER BY STUDY_ID;
