USE DATABASE ACT_DB;
USE SCHEMA CONTROL;

ALTER TABLE PIPELINE_ALERT
    ADD COLUMN IF NOT EXISTS RESOLVED_AT TIMESTAMP_LTZ;

ALTER TABLE PIPELINE_ALERT
    ADD COLUMN IF NOT EXISTS RESOLVED_BY_DAG_RUN_ID VARCHAR;

COMMENT ON COLUMN PIPELINE_ALERT.RESOLVED_AT IS
'Timestamp when a later successful execution resolved the operational alert';

COMMENT ON COLUMN PIPELINE_ALERT.RESOLVED_BY_DAG_RUN_ID IS
'Airflow DAG run ID whose successful task execution resolved the alert';